### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'weights/mobilenetv2\\custom_logits_semantic_kernel.npy'

### ISSUE THREAD

**Issue by Sylvia1018** [bonlime/keras-deeplab-v3-plus#103]
When I run the load_data.py,there appears this error, does anyone have any idea about this issue? Many thanks in advance.

**Comment by shubhaminnani** [comment]
can you please give the solution same problem here

**Comment by shubhaminnani** [comment]
@Sylvia1018 can you please give the solution

**Comment by Sylvia1018** [comment]
Hi,sorry for the late reply. Since I only conduct the inference using the pretrained weight, I simply change the sentence here: '
    else:
        last_layer_name = 'custom_logits_semantic'' 
this sentence in model.py 437-438, and it works. Guess it is because that this two lines the weight of customed layers.
then this part looks like 
   x = Dropout(0.1)(x)

    # DeepLab v.3+ decoder

    last_layer_name = 'custom_logits_semantic'

    x = Conv2D(classes, (1, 1), padding='same', name=last_layer_name)(x)
    x = BilinearUpsampling(output_size=(input_shape[0], input_shape[1]))(x)

Hope this can help!

**Comment by shubhaminnani** [comment]
'weights/xception\\custom_logits_semantic_kernel.npy this file is missing but i edited above like code but not working . Can you upload full decoder part? Thank you in advance

**Comment by shubhaminnani** [comment]
@Sylvia1018

**Comment by Sylvia1018** [comment]
Hi, in the following is the part, you can notice that I only change the last part when you need to specify the weights and classes:)
 # Image Feature branch
    shape_before = tf.shape(x)
    b4 = GlobalAveragePooling2D()(x)
    b4 = tf.expand_dims(tf.expand_dims(b4, 1),1) # from (b_size, channels)->(b_size, 1, 1, channels)
    b4 = Conv2D(256, (1, 1), padding='same',
                use_bias=False, name='image_pooling')(b4)
    b4 = BatchNormalization(name='image_pooling_BN', epsilon=1e-5)(b4)
    b4 = Activation('relu')(b4)
    #upsample. have to use compat because of the option align_corners
    b4 = Lambda(lambda x: tf.compat.v1.image.resize(x, shape_before[1:3], 
                                                    method='bilinear',align_corners=True))(b4) 

    # simple 1x1
    b0 = Conv2D(256, (1, 1), padding='same', use_bias=False, name='aspp0')(x)
    b0 = BatchNormalization(name='aspp0_BN', epsilon=1e-5)(b0)
    b0 = Activation('relu', name='aspp0_activation')(b0)

    # there are only 2 branches in mobilenetV2. not sure why
    if backbone == 'xception':
        # rate = 6 (12)
        b1 = SepConv_BN(x, 256, 'aspp1',
                        rate=atrous_rates[0], depth_activation=True, epsilon=1e-5)
        # rate = 12 (24)
        b2 = SepConv_BN(x, 256, 'aspp2',
                        rate=atrous_rates[1], depth_activation=True, epsilon=1e-5)
        # rate = 18 (36)
        b3 = SepConv_BN(x, 256, 'aspp3',
                        rate=atrous_rates[2], depth_activation=True, epsilon=1e-5)

        # concatenate ASPP branches & project
        x = Concatenate()([b4, b0, b1, b2, b3])
    else:
        x = Concatenate()([b4, b0])

    x = Conv2D(256, (1, 1), padding='same',
               use_bias=False, name='concat_projection')(x)
    x = BatchNormalization(name='concat_projection_BN', epsilon=1e-5)(x)
    x = Activation('relu')(x)
    x = Dropout(0.1)(x)
    # DeepLab v.3+ decoder

    if backbone == 'xception':
        # Feature projection
        # x4 (x2) block
        x = Lambda(lambda xx: tf.compat.v1.image.resize(xx,
                                                x.shape[1:3]*tf.constant(OS//4),
                                                method='bilinear', align_corners=True))(x) 
        dec_skip1 = Conv2D(48, (1, 1), padding='same',
                           use_bias=False, name='feature_projection0')(skip1)
        dec_skip1 = BatchNormalization(
            name='feature_projection0_BN', epsilon=1e-5)(dec_skip1)
        dec_skip1 = Activation('relu')(dec_skip1)
        x = Concatenate()([x, dec_skip1])
        x = SepConv_BN(x, 256, 'decoder_conv0',
                       depth_activation=True, epsilon=1e-5)
        x = SepConv_BN(x, 256, 'decoder_conv1',
                       depth_activation=True, epsilon=1e-5)

    # you can use it with arbitary number of classes
    #if (weights == 'pascal_voc' and classes == 21) or (weights == 'cityscapes' and classes == 19):
    last_layer_name = 'logits_semantic'
    #else:
    #    last_layer_name = 'custom_logits_semantic'

    x = Conv2D(classes, (1, 1), padding='same', name=last_layer_name)(x)
    x = Lambda(lambda xx: tf.compat.v1.image.resize(xx,
                                                   tf.shape(img_input)[1:3],
                                                   method='bilinear',align_corners=True))(x)
