### ISSUE TITLE
 Failed to convert object of type <class 'tuple'> to Tensor

### ISSUE THREAD

**Issue by shubhaminnani** [bonlime/keras-deeplab-v3-plus#104]
while running load_weights.py getting this error 

File "C:\Users\Student\Anaconda2\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 562, in make_tensor_proto
    "supported type." % (type(values), values))

TypeError: Failed to convert object of type <class 'tuple'> to Tensor. Contents: (1, 1, 16, Dimension(96)). Consider casting elements to a supported type.

**Comment by gi097** [comment]
I get the same error. What did you do to resolve this issue?

**Comment by shubhaminnani** [comment]
use keras 2.2 and tensorflow 1.XX and use the previous version code.
