### ISSUE TITLE
Issue with number of classes

### ISSUE THREAD

**Issue by shubhaminnani** [bonlime/keras-deeplab-v3-plus#114]
If I change number of classes to train, do I need to change it in load_weights.py? After changing in load_weights.py it is showing error of classes didn't match. Thanks in advance @bonlime

**Comment by bonlime** [comment]
You don't need to change anything in load_weights. Just instantiate the model with `classes={your number here}` as shown in the README

**Comment by shubhaminnani** [comment]
ok thank you
