### ISSUE TITLE
keras and tensorflow version for installation

### ISSUE THREAD

**Issue by wenouyang** [bonlime/keras-deeplab-v3-plus#15]
Hi Bonlime,

Thanks for sharing the code, would you like to clarify which version of tensorflow and keras you are supporting?  It seems to me that the original deeplab V3 code only works for tensorflow=1.5.

**Comment by niketb** [comment]
Yes, I want to know this too.

**Comment by bonlime** [comment]
I'm using 
Keras==2.1.5
tensorflow-gpu==1.6.0
with CUDA 9
