### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by lsymuyu** [bonlime/keras-deeplab-v3-plus#18]
Could you please give an example or some ideas to train on new dataset? Thanks in advance.

**Comment by lsymuyu** [comment]
It seems pre-processing is necessary to expand the dimension of labels from [w, h] to [w, h, num-classes]?
How could i do this ? Thanks.

**Comment by bonlime** [comment]
@lsymuyu 
You can use this gist to convert categorical labels to 3d 
https://gist.github.com/frnsys/91a69f9f552cbeee7b565b3149f29e3e

**Comment by zyfsa** [comment]
hello, bonlime. I am using the model in our own dataset. I found the result is very, very pool?do you have suggestion? I  have 3 classes, one of them is background. I am trouble. I process in [-1,1].Besides, pad (384,512,3) to (512,512,3) as your readme.txt.
I also want to know my class is 3,not 21,do you have an influence on the load weights.

**Comment by bonlime** [comment]
@zyfsa 
Yes it has an influence on weight load. Because your number of classes is not equal to 21, last layers are initialized randomly

**Comment by daxiaoshu** [comment]
@bonlime  
  I am using the model in our own dataset.,  data_shape=(384,384,3),   ValueError: Negative dimension size caused by subtracting 32 from 24 for 'average_pooling2d_1/AvgPool' (op: 'AvgPool') with input shapes: [1,24,24,2048],can you tell me what it hapen ?

**Comment by vodp** [comment]
@daxiaoshu  Down under the path, the network reduces spatial dimensions to achieve abstraction. So 384 is too small  for the tensor to go through till the last layer.
