### ISSUE TITLE
How to create masks?

### ISSUE THREAD

**Issue by mttlutkarsh** [bonlime/keras-deeplab-v3-plus#23]
I have 2 classes in my target segmented image. So that means I have a greyscale mask of height x width consisting of 0s and 1s. Using expand_dims I can get a mask of shape (height, width, 1) but when specifying classes=2, the model expects masks of shape (height, width, 2). How to create such mask?

**Comment by bonlime** [comment]
you can specify classes=1 and it should work well

**Comment by mttlutkarsh** [comment]
@bonlime okay, thanks! That's what I tried. It is training. Let us wait for the results. Thanks for this amazing work.
