### ISSUE TITLE
Training on uint8 [0...255] images instead of [-1...1]?

### ISSUE THREAD

**Issue by mttlutkarsh** [bonlime/keras-deeplab-v3-plus#24]
What will be the effect of training on images with values in the range 0-255, that is, not using the pre-processing function provided in models.py?
Due to memory limitations, I can't assign float64 array and had to use ubyte only, but this gave me very poor, random and fluctuating results on epochs.

**Comment by bonlime** [comment]
I'm not sure you can do it. Some models, like MobileNetv2 could be inferenced with int8 , but during training you have to use floats to make small adjustments to your weights anyway. Also TF is using floats inside it graph, so using 0-255 images will have litteraly no effect on memory consumption, but will lead to worse result

**Comment by vodp** [comment]
@mttlutkarsh you should train with float32 and then try using quantization on the network at inference stage.
