### ISSUE TITLE
Weird looking output

### ISSUE THREAD

**Issue by dmus** [bonlime/keras-deeplab-v3-plus#29]
When I run the following code:

```
import tensorflow as tf
from matplotlib import pyplot as plt
import cv2 # used for resize. if you dont have it, use anything else
import numpy as np
from model import Deeplabv3
import time
import pdb

model = Deeplabv3(input_shape=(427,640,3), backbone='xception', classes=21)

img = cv2.imread('imgs/image1.jpg')

input = cv2.cvtColor(img, cv2.COLOR_BGR2RGB) / 127.5 - 1
res = model.predict(np.expand_dims(input, 0))

labels = np.argmax(res.squeeze(),-1)

plt.imshow(labels)
plt.show()
```

the result looks like this.
![figure_1](https://user-images.githubusercontent.com/464378/41847478-68dfbf02-787a-11e8-98d8-ae84c1859bc1.png)
 This is not what I expect. What is going wrong here?

**Comment by bonlime** [comment]
Your code looks totally OK. I don't know what is the reason for such strange behavior. If you will find it out, share with me.

**Comment by vamshireddyp** [comment]
Try to change the image. Then we can think for an explanation
