### ISSUE TITLE
Does the model have errors?

### ISSUE THREAD

**Issue by Taylor-Rose** [bonlime/keras-deeplab-v3-plus#30]
When I use fit, it says
Error when checking target: expected bilinear_upsampling_2 to have shape (512, 512, 2) but got array with shape (512, 512, 3)
ps: My input image.shape is (512,512,3)

**Comment by kritiyer** [comment]
I also got this error, @Taylor-Rose did you find a solution? My input shape is (572,572,3) and my error message is: 

`ValueError: Error when checking target: expected bilinear_upsampling_2 to have shape (572, 572, 2) but got array with shape (572, 572, 1)`

**Comment by bonlime** [comment]
@kritiyer  double check that your labels are as expected. Maybe you need to set a number of classes to 2.

**Comment by kritiyer** [comment]
Thank you for the quick response! I have 1 object class and 1 background class, so would number of classes be 1 or 2? Also, should the labels be single channel images?

**Comment by bonlime** [comment]
Depends on your loss. If you use sigmoid, you don't even need background class. If you use softmax then you need it. labels should be multichannel

**Comment by kritiyer** [comment]
Sorry if this is a silly question, should I add a sigmoid or softmax activation function to the last layer of the model then? I am using binary_crossentropy loss.

**Comment by kritiyer** [comment]
#54 answers my above question about softmax
