### ISSUE TITLE
Score map 

### ISSUE THREAD

**Issue by acecreamu** [bonlime/keras-deeplab-v3-plus#32]
Hi, 
I am quite new, could give an advise, how to obtain score map (input before softmax function) and visualize  it using colormap?
The one like https://i.imgur.com/rfUyXez.png 

And also, how much gpu-memory pre-trained model requires to run? I got "run out of memory" error using 2 Gb GPU.

Thank you in advance.

**Comment by bonlime** [comment]
I don't know exactly how much GPU memory you need, but 2GB should be enough for a MobileNet backbone. 
To get a score map for a particular class use "How to get labels" example from README, but change
`labels = np.argmax(res.squeeze(),-1)` to `labels = res.squeeze()[:, :, *desired class label*]`
You can find classes labels here https://github.com/NVIDIA/DIGITS/blob/master/examples/semantic-segmentation/pascal-voc-classes.txt
