### ISSUE TITLE
new starter - confused with the resizing part in the example

### ISSUE THREAD

**Issue by minjiacheng** [bonlime/keras-deeplab-v3-plus#33]
So I'm very new to python and I was trying to use the example code given in README but with my own images:
from matplotlib import pyplot as plt
import cv2 # used for resize. if you dont have it, use anything else
import numpy as np
from model import Deeplabv3
deeplab_model = Deeplabv3()
img = plt.imread("imgs/image1.jpg")
w, h, _ = img.shape
ratio = 512. / np.max([w,h])
resized = cv2.resize(img,(int(ratio*h),int(ratio*w)))
resized = resized / 127.5 - 1.
pad_x = int(512 - resized.shape[0])
resized2 = np.pad(resized,((0,pad_x),(0,0),(0,0)),mode='constant')
res = deeplab_model.predict(np.expand_dims(resized2,0))
labels = np.argmax(res.squeeze(),-1)
plt.imshow(labels[:-pad_x])

I get the following error message:
ValueError: Error when checking input: expected input_3 to have shape (512, 512, 3) but got array with shape (512, 389, 3)

I've also tried to add the line
deeplab_model = Deeplabv3(input_shape=(384,384,3), classes=4)  
but still receive the same error message but this time expecting input to have shape (384, 384, 3) 

When I try to pre-process the images by resize them to the required shape i get this error instead:
3443: UserWarning: Attempting to set identical bottom==top results
in singular transformations; automatically expanding.
bottom=-0.5, top=-0.5
  'bottom=%s, top=%s') % (bottom, top))
And the image output becomes a flat line.

Any help would be much appreciated.

**Comment by bonlime** [comment]
Sorry for the long answer. Your error could be fixed by using:
```
pad_x = int(512 - resized.shape[0])
pad_y = int(512 - resized.shape[1])
resized2 = np.pad(resized,((0,pad_x),(0,pad_y),(0,0)),mode='constant')
```
instead of 
```
pad_x = int(512 - resized.shape[0])
resized2 = np.pad(resized,((0,pad_x),(0,0),(0,0)),mode='constant')
```

**Comment by kernel1994** [comment]
and need to change the last line to
`plt.imshow(labels[:512 - pad_x, :512 - pad_y])`
