### ISSUE TITLE
AttributeError: 'module' object has no attribute 'normalize_data_format'

### ISSUE THREAD

**Issue by yifaliu** [bonlime/keras-deeplab-v3-plus#34]
Hi, when I run the example shown in the readme.md using image1.jpg, I got the error: 

AttributeError: 'module' object has no attribute 'normalize_data_format'

Do you guys have any ideas about this error? Thanks

**Comment by bonlime** [comment]
It looks like a Keras issue. Probably you're using a newer version and syntaxes has changed

**Comment by yifaliu** [comment]
Thank you. 
I solved it.
The normalize_data_format() has been moved from conv_utils.py to common.py in keras.
