### ISSUE TITLE
Load weights whith another number of classes

### ISSUE THREAD

**Issue by arthurPrvst** [bonlime/keras-deeplab-v3-plus#35]
I used extract_weights to get weights from the pretrained network on _PASCAL VOC_, and I'm loading these weights after a init of the model with random weights, with a classes=3 :

```
      WEIGHTS_DIR = 'weights/' + backbone 
      print('Loading weights from', WEIGHTS_DIR) 
      for layer in tqdm(model.layers): 
          if layer.weights: 
              weights = [] 
              for w in layer.weights: 
                  weight_name = os.path.basename(w.name).replace(':0', '') 
                  weight_file = layer.name + '_' + weight_name + '.npy' 
                  weight_arr = np.load(os.path.join(WEIGHTS_DIR, weight_file)) 
                  weights.append(weight_arr) 
              layer.set_weights(weights) 
```

I get an error :` Layer weight shape (1, 1, 256, 3) not compatible with provided weight shape (1, 1, 256, 21)` Should I merge the weights over the 21 channels of your last layer, to get weights for only 3 channels  (because logits_semantic_bias.npy has a shape (21,) and logits_semantic_kernel.npy has a shape (1, 1, 256, **21**)? Thanks in advance

**Comment by bonlime** [comment]
Hi. PASCAL VOC has 21 classes, so loading all the weights into the model with 3 classes will raise an error at last layer (which you eventually got). 
Instead of using load weights script use example from README
```
deeplab_model = Deeplabv3(input_shape=(384,384,3), classes=3)
```
This code will load all weights except for the last layer

**Comment by arthurPrvst** [comment]
Thanks for the answer. Because weights from the last layer are not as usefull as weights for first layers, I agree with you. That's why I decided to forgot about them. But merging them (like average), can be another solution (it can be better than an init with` 'he'`).
