### ISSUE TITLE
Training with tf.data

### ISSUE THREAD

**Issue by dmus** [bonlime/keras-deeplab-v3-plus#36]
I would like to train this model with some data coming from an tf.data.Dataset.

```
model.fit(dataset.make_one_shot_iterator(),
          steps_per_epoch=10,
          epochs=5)
```
This should be able to work, however it looks like it still expects a numpy array as input for the model.fit method. The error message is 

> Traceback (most recent call last):
>   File "train.py", line 91, in <module>
>     epochs=5)
>   File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1630, in fit
>     batch_size=batch_size)
>   File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 1476, in _standardize_user_data
>     exception_prefix='input')
>   File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 76, in _standardize_input_data
>     data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
>   File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 76, in <listcomp>
>     data = [np.expand_dims(x, 1) if x is not None and x.ndim == 1 else x for x in data]
> AttributeError: 'Iterator' object has no attribute 'ndim'

Is this possible in an easy way?

**Comment by bonlime** [comment]
I've never tried using tf.data for training keras model, but you can use code from here:
https://gist.github.com/datlife/abfe263803691a8864b7a2d4f87c4ab8
Also, I'll close this issue because it's a keras problem, not this repo's
