### ISSUE TITLE
Stride value not consistent with paper

### ISSUE THREAD

**Issue by Bonnie970** [bonlime/keras-deeplab-v3-plus#48]
Hello,

Should the stride value at here: https://github.com/bonlime/keras-deeplab-v3-plus/blob/b90de745612df2f367649f64b8ea47b9108618fa/model.py#L371 https://github.com/bonlime/keras-deeplab-v3-plus/blob/b90de745612df2f367649f64b8ea47b9108618fa/model.py#L372  be 2 instead of 1 based on the paper? 

Thanks.

**Comment by bonlime** [comment]
You probably refer to this image in paper:
![image](https://user-images.githubusercontent.com/14337581/46559150-fd0dab00-c8b4-11e8-84dc-1feb57e9fc2b.png)
but it shows original Xception
in Deeplab the second exit block uses dilation rate=2 to compencate unexisting stride=2 in block 1
