### ISSUE TITLE
Bilinear upsample

### ISSUE THREAD

**Issue by bhack** [bonlime/keras-deeplab-v3-plus#49]
It is available upstream https://github.com/keras-team/keras/pull/10994

**Comment by bonlime** [comment]
The model weights require to use `align_corners` parameter with upsampling. Right now it is not supported in Keras version

**Comment by bhack** [comment]
@bonlime Thanks for commenting upstream.

**Comment by bonlime** [comment]
Moved to TF Keras (https://github.com/bonlime/keras-deeplab-v3-plus/commit/64bc7a86422c3ff27c4c7e96c1a640d1ec4eb438) , got rid of custom Bilinear Upsample layer in favor of Lambda layer 
as suggested in https://github.com/tensorflow/tensorflow/issues/23041#issuecomment-430712751
