### ISSUE TITLE
Training

### ISSUE THREAD

**Issue by Zumbalamambo** [bonlime/keras-deeplab-v3-plus#5]
How do I train on a custom dataset?

**Comment by bonlime** [comment]
`from model import Deeplabv3   `
`deeplab_model = Deeplabv3((512,512,3), num_classes=4, last_activation=True, OS=16)  `
`deeplab_model.load_weights('deeplabv3_weights_tf_dim_ordering_tf_kernels.h5', by_name = True)`

after that, you will have a usual Keras model, which you can train using fit, or fit_generator  
if you want more detailed description, google any Keras tutorials  
 There are few important moments with this model:
1. It is important to have a big batch to train BN layers properly, in order to do that you can train with OS 16 and inference with OS 8
2. you can also freeze first 356 layers and train only decoder with big batch size first, then unfreeze all layers and train with smaller batch size

**Comment by kli017** [comment]
I try to initial the model by 
deeplab_model = Deeplabv3((512,512,3), num_classes=4, last_activation=True, OS=16)
by the get below error
TypeError: Deeplabv3() got an unexpected keyword argument 'num_classes'

**Comment by bonlime** [comment]
@kli017 interface changed a little bit. Look at the new one in README

**Comment by kli017** [comment]
@bonlime Thanks! The new one in README has a parameter named 'weighs' , however in the model.py the parameter is 'weights'. I tried both of them but still get error

deeplab_model = Deeplabv3((960,1440,3), classes=4, weighs = None, OS=16)
TypeError: Deeplabv3() got an unexpected keyword argument 'weighs'

**Comment by bonlime** [comment]
Sorry, it was typo. Correct version is "weights", you should have problems with it

**Comment by kli017** [comment]
Hello, I also tried 'weights' with both None and 'pascal_voc'. But still got TypeError...
TypeError: Deeplabv3() got multiple values for keyword argument 'weights'

**Comment by raghavmallick** [comment]
@kli017 Try using the arguments in the following format: 
Deeplabv3(weights='pascal_voc', input_tensor=None, input_shape=(512, 512, 3), classes=21, OS=16)

This worked for me

**Comment by bonlime** [comment]
@kli017  the reason why you get TypeError is because you pass input_shape as first argument without explicitly naming it.  all parameters you pass into this model have to be named

**Comment by bhack** [comment]
Could make sense to load and freeze  low-level only weights? https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#model-details-2

**Comment by bonlime** [comment]
@bhack you're right, the model is really big. On my 1080ti it is possible to train only with a batch size of 6 images. 
Yeah, it can make sense to freeze low-level features. Adding only ImageNet pre-trained xception is already in my checklist

**Comment by wenouyang** [comment]
@bhack, the link you shared is the tensorflow-based weights, how can I load it in the keras model, please advise. 
 Thanks

https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md#model-details-2

**Comment by bonlime** [comment]
@Taylor-Rose you don't need to do that anymore. Now weights are loaded if you pass "weights" argument

**Comment by Taylor-Rose** [comment]
@bonlime I did some code like this:
`
model = Deeplabv3()
model.summary()
model.fit(train_data,label_data, epochs etc.)
`
I found that there is no function like 'sigmoid' or 'softmax' on the last layer of the model. In the U-net model I found the function like 'sigmoid' or 'softmax'. What I want to ask is that can I use model.fit() directly after model=Deeplabv3() without any other process.  The second I want to ask is that the input data's formation. Does train_data's formation like (512,512,3) with 3 dimension and label_data's formation also like (512,512,3) or should do some preprocess to (class_num, 512,512,3) or other formation?

**Comment by bhack** [comment]
@bonlime Are the `extract_weights/load_weights` recovering the BN mean and variance? Check https://github.com/keras-team/keras/issues/3423#issuecomment-389770359.

**Comment by bhack** [comment]
@bonlime See also this long topic https://github.com/keras-team/keras/pull/9965

**Comment by bonlime** [comment]
@bhack  sorry for the long answer. Both moving mean and variance are recovered correctly. 
btw. Thanks for pointing out the problem with frozen BN. What kind of work around this problem do you personally use?

**Comment by JackMing1986** [comment]
How long can I finish training?

**Comment by ChengxiHAN** [comment]
Have u guys trained new datasets and fine tuned successfully？plz tell me，I wanna try......

**Comment by margokhokhlova** [comment]
Hello everyone! Can someone give me an advice, please? I want to try the model on a binary segmentation, shall I add a sigmoid activation to the last model output?

**Comment by pluniak** [comment]
@ChengxiHAN @margokhokhlova Did you read issue #56? Yes sigmoid activation on the last layer. I have fine-tuned successfully, but freezing BN-layers while finetuning might cause problems.

**Comment by margokhokhlova** [comment]
@pluniak Thank you!  Reading it.

**Comment by Cris-qu** [comment]
> @bonlime I did some code like this:
> `model = Deeplabv3() model.summary() model.fit(train_data,label_data, epochs etc.)`
> I found that there is no function like 'sigmoid' or 'softmax' on the last layer of the model. In the U-net model I found the function like 'sigmoid' or 'softmax'. What I want to ask is that can I use model.fit() directly after model=Deeplabv3() without any other process. The second I want to ask is that the input data's formation. Does train_data's formation like (512,512,3) with 3 dimension and label_data's formation also like (512,512,3) or should do some preprocess to (class_num, 512,512,3) or other formation?

Hollow.Have you successfully run this model?I got an errror :AttributeError: 'ModelCheckpoint' object has no attribute 'on_train_batch_begin'
I used fit_generator to get train data and val data.

**Comment by Zumbalamambo** [comment]
@Cris-qu Yes it works perfectly at the moment

**Comment by Zumbalamambo** [comment]
@ChengxiHAN It works fine once we train with the custom dataset. The accuracy was fair enough
