### ISSUE TITLE
 ValueError in bilinear_upsampling due to mismatch in shape

### ISSUE THREAD

**Issue by asdspal** [bonlime/keras-deeplab-v3-plus#52]
Hi,
I'm getting error  "
**ValueError: Error when checking target: expected bilinear_upsampling_5 to have shape (101, 101, 2) but got array with shape (101, 101, 1)**". This happens during xception as well as mobilenetv2. 
my train img_size = (101,101)

can someone please tell me what's wrong?

**Comment by bonlime** [comment]
How many classes do you have? Try setting number of classes to 1

**Comment by asdspal** [comment]
Thanks, I get it now. I have  to predict a single class.
