### ISSUE TITLE
Can you release your complete code？

### ISSUE THREAD

**Issue by sunjunee** [bonlime/keras-deeplab-v3-plus#53]
Hi,
I am a newcomer to learn keras. I'd like to ask that could you please release your complete code here? 
Thank you in advance.

**Comment by bonlime** [comment]
What do you mean by "complete code"?

**Comment by sunjunee** [comment]
@bonlime  Thanks for your reply. I mean could you please release your training code here? I got some problems in training procedure and wanted to learn from you.

**Comment by bonlime** [comment]
@sunjunee I haven't trained this model, I only transformed the pretrained weights from TF format to Keras format.
