### ISSUE TITLE
OS=16 get better result than OS=8 in my val dataset 

### ISSUE THREAD

**Issue by uniquezhengjie** [bonlime/keras-deeplab-v3-plus#60]
hi,you said Xception backbone should be trained with OS=16, and only inferenced with OS=8,but OS=16 get better result than OS=8 in my val dataset  ,why?
```
os=8 0.7820307191530157 0.8163021613035841 0.6259312247569429
os=16 0.7855338935948276 0.8200502315806699 0.6927438598873709
```

**Comment by uniquezhengjie** [comment]
yes , i have.I am very confused about this result.Has anyone else got results similar to me?

**Comment by bonlime** [comment]
@uniquezhengjie 
The intuition behind suggesting to use OS=8 for inference is that it would provide a dense prediction map in the bottleneck, losing less information. 
Can you share your fine-tuning results of this model? For me it looks like it's impossible to fine-tune it for another task.
