### ISSUE TITLE
Are there any changes in the backbone networks?

### ISSUE THREAD

**Issue by AakashKumarNain** [bonlime/keras-deeplab-v3-plus#68]
I see that we can use `Xception` and `Mobilenetv2` as the feature extractor. Are there any changes in these backbone networks for feature extraction than the one that is provided in the official [keras applications](https://keras.io/applications/)? Because if there are no changes, we can trim a lot of code from the `model.py` file

**Comment by bonlime** [comment]
Hi, 
I used the code from keras application as a reference, but the backbones here are a little different. You can read about in the paper (the didn't actually mentioned everything they changed, I had to figure some things out by myself), or you can compare the code, it's pretty easy to see the difference

**Comment by bonlime** [comment]
The code was written a year ago. Now keras has it's own bilinear resize, you can probably remove this part from model.py
But be aware that you must pass 'align corners" parameter. Last time when I checked it, it was impossible to pass this parameter using keras. If you'll manage to do it, feel free to make a pull request.
