### ISSUE TITLE
ValueError: Error when checking target: expected bilinear_upsampling_3 to have shape (512, 512, 21) but got array with shape (512, 512, 1)

### ISSUE THREAD

**Issue by ganyeshprasanna** [bonlime/keras-deeplab-v3-plus#7]
This is the error I get when I try to train the model using the PASCAL VOC 2012 dataset. Is it because of some problem with the one hot encoding? What am I missing out on? I am not very sure why it throws the error

**Comment by Meight** [comment]
I'm encountering the same problem. Any clue on how to solve this?
