### ISSUE TITLE
compatibility with tensorflow < 2.0

### ISSUE THREAD

**Issue by tsing90** [bonlime/keras-deeplab-v3-plus#74]
Hi, as I have cuda 9.0 in Ubuntu 16.04, so tensorflow 2.0 is not an option (tensorflow 1.12 installed instead). when I run the code: 

`from model import Deeplabv3`
'model=Deeplabv3(input_shape=(None,None,3), backbone='xception',OS=8)`
I got an error:
`AttributeError: module 'tensorflow._api.v1.image' has no attribute 'resize'`

How can I resolve this so that I can run the code in tensorlow 1.120 ? 
many thanks

**Comment by bonlime** [comment]
Hi. I updated it to TF 2.0 only 2 days ago. You can get an older commit which works perfectly for TF 1.13 and Keras 2.2.4.

**Comment by bonlime** [comment]
added instruction in https://github.com/bonlime/keras-deeplab-v3-plus/commit/34e1a1dffd53a90c4de7d600ced3eb746c3dae1a

**Comment by tsing90** [comment]
great, it worked! thanks for your prompt reply. 
by the way, in the older commit, I have to specify the input shape, but your newest code support any input size (None, None). How can I update the older code so that it could do the same job? such as add code like as follow ?
`b4 = Lambda(lambda x: tf.image.resize(x, shape_before[1:3], 
                                                    method='bilinear',align_corners=True))(b4) `

**Comment by bonlime** [comment]
Yeap. Code is going to be exactly the same. The only thing that is different - you will use `tf.image.resize` instead of `tf.compat...`

**Comment by tsing90** [comment]
Hi, after modifying several lines of code, I got an error on the following line:
`line 514, in Deeplabv3
    model = Model(inputs, x, name='deeplabv3plus')
line 1695, in build_map_of_graph
    layer, node_index, tensor_index = tensor._keras_history
AttributeError: 'Tensor' object has no attribute '_keras_history'
`
any reason for this issue? thank you

**Comment by bonlime** [comment]
I don't know what causes this issue. Hope you will figure it out yourself

**Comment by ZhonghuaTian** [comment]
module 'tensorflow._api.v2.train' has no attribute 'NewCheckpointReader'
