### ISSUE TITLE
The path to the pre-trained weights does not exist anymore

### ISSUE THREAD

**Issue by margokhokhlova** [bonlime/keras-deeplab-v3-plus#81]
Can I ask u where it can be found?
looks like the link is broken

**Comment by pluniak** [comment]
@margokhokhlova Check this repo for weights. You can find Xception weigths, too (under closed issues): Golbstein/Keras-segmentation-deeplab-v3.1

**Comment by bonlime** [comment]
@margokhokhlova it works perfectly fine for me. Here is the code i used to test:
```
from model import Deeplabv3
for backbone in {'xception','mobilenetv2'}:
  for weight in {'pascal_voc', 'cityscapes'}:
    deeplab_model = Deeplabv3(weights=weight,backbone=backbone);

print("test passed")
```
which pretrained weights failed to load in your case?

**Comment by margokhokhlova** [comment]
thank you very much for your answer!
It couldn't find & download the data automatically, maybe I have done smth wrong. I will try again, so far I just changed the path to the weights needed and it worked!
TF_WEIGHTS_PATH = "https://github.com/bonlime/keras-deeplab-v3-plus/releases/download/1.2/deeplabv3_xception_tf_dim_ordering_tf_kernels_cityscapes.h5"
