### ISSUE TITLE
Problem with loading trained model

### ISSUE THREAD

**Issue by dhlee-jubilee** [bonlime/keras-deeplab-v3-plus#84]
Training was well, but the trained model is not loaded.
I followed the guideline, 

from model import relu6
deeplab_model = load_model('example.h5',custom_objects={'relu6':relu6})

but still "Unknown layer: BilinearUpsampling" error.

Should I use TF 2.0?

**Comment by bonlime** [comment]
Hi, this error occurs due to model updated readme. If you also import bilinear upsample layer and pass it to load_model everything should be fine
