### ISSUE TITLE
Deeplabv3() got an unexpected keyword argument

### ISSUE THREAD

**Issue by PhuongHang** [bonlime/keras-deeplab-v3-plus#9]
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:/Users/pdrt/Desktop/keras-deeplab-v3-plus/load_weights.py", line 16, in <module>
    model = Deeplabv3(input_shape=(512, 512, 3),num_classes = 21)
TypeError: Deeplabv3() got an unexpected keyword argument 'num_classes'
Instantiating an empty Deeplabv3+ model...

Why? How can I fix thiss?

**Comment by bonlime** [comment]
I forgot to fix the README. use "classes" argument instead

**Comment by PhuongHang** [comment]
many thanks
