### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

### ISSUE THREAD

**Issue by yangxingyu588** [bonlime/keras-deeplab-v3-plus#91]
why I have this error,how to solve this problem?thank you
python 3.7

**Comment by bonlime** [comment]
This is a basic python error which is pretty obvious and not related to this repo.

**Comment by sachsbl** [comment]
try this repo for my attempt at a beginner-friendly quickstart for this:
https://github.com/sachsbl/segmental
