### ISSUE TITLE
Cannot save model 

### ISSUE THREAD

**Issue by ssakhavi** [bonlime/keras-deeplab-v3-plus#95]
I am trying to save the mode during the callbacks.
I'm getting this error: 
`can't pickle _thread.RLock objects`

**Comment by vbedecs** [comment]
I have same problem:

Exception has occurred: TypeError
can't pickle _thread.RLock objects

Is there anyone with solution to this?

**Comment by iariav** [comment]
same

**Comment by ssakhavi** [comment]
I managed to solve the problem. 
I've submitted a pull request:
#102

**Comment by brianmanderson** [comment]
This seemed to become a problem again, I updated the code to use Keras Bilinear upsampling instead of the tensorflow resize_images, also a few other things to keep it all within tensorflow.python.keras
submitted a pull request:
#137

**Comment by brianmanderson** [comment]
problem was that a tensor was being passed to the image.resize at line 409, fixed now by including int_shape
#141
