### ISSUE TITLE
model.py broken

### ISSUE THREAD

**Issue by changbaishan** [bonlime/keras-deeplab-v3-plus#97]
As a result of tensorflow releases, imports in model.py no longer hold. Can you please fix your code? Thanks.

**Comment by sachsbl** [comment]
I created a PR to fix this.  
https://github.com/bonlime/keras-deeplab-v3-plus/pull/101 
Please in the future consider a PR, rather than a request/issue.  I do not think the maintainer of this repo has a ton of free time (probably has a job as a badass data scientist or something ;-) )

**Comment by changbaishan** [comment]
Thanks Ben.
________________________________
