### ISSUE TITLE
TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

### ISSUE THREAD

**Issue by sharmarochan** [bonlime/keras-deeplab-v3-plus#99]
While testing DeepLabv3 getting error as :
in __call__:
 scale /= max(1., (fan_in + fan_out) / 2.)

TypeError: unsupported operand type(s) for /: 'Dimension' and 'float'

Before running the model I made sure all the pre-requirements :

cuda-9.0
tensorflow-gpu>1.13
Keras 2.2.4 
are satisfied. Any help will be appreciated.

screenshot is attached for reference

![error](https://user-images.githubusercontent.com/22585459/57522298-ed20e280-733f-11e9-99d8-042e258b1cd9.png)

**Comment by sachsbl** [comment]
If you are on the latest (Master) branch of this repo, you need to explicitly install TensorFlow 2.0 Alpha.  
Use `pip install tensorflow==2.0.0a0`

**Comment by sharmarochan** [comment]
Thanks. It helped.
